# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_teaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_teaser_teaser', serialize=False, to='cms.CMSPlugin'),
        ),
    ]